language: node_js
script:
  - yarn test
after_success:
  - yarn test:coverage
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: pdFrnKo4Ms9QgzFJh6h7QO9qBPqfe/CfWhVn5r/pnN+xlOpCyGHFF8OTqcXgseLlcu0RA91D5KzwwGFLOTzgtx+wZi2epI0rYWTkn+FDSCh3vV7O/6EgOBzWm4Ip1IxA89WuT+yay+hVDj8TVudQRDaP2grGjTgXgeG47Shva/8H5+ipZeBeDPyxAGp/hEhZ7ZqxMooOPspAJqb999FTXCT8RH7ujhBahFTGQYwOFDiNF9Bhixofe55G7Hsfp1mQSjcPCpNvSJRwPtFoIAapA+b4BL+ChG2007ka3oY3kh3SIkS9mBqqgYqHjDUvLeGtSbp3FiqBfZGEo1YYym75ThUBlhYxNvGyPDiDjWgvsbNkkhV2IXP0eO4hHw0nixEk0SLKksCrdYPZjolZl4iUBgfBQtp+GxNakwO3J8OO6JauSZtqGB9siV65ytkT4eiQ4mVs6b+Pl4bmg6hoSLjrVxVnr6zW+8x10X1XMSqZCN9vh3CjMzI875ScGAjhHTfghbEqq+rLJjhvDkTKC0EuP5XRl4sSV9POKNDP/9FD/cOs3YErngpiEdqprXv9uNhE6s+PO+9RlB8KoIHMghmacQv2CuyD0vVyKGcLjoY8jw+xONc9wQg8tYJdG8L3hfmnrUQVcKgUoaypeY/Q0HAcr1cNvqxkkSD/ix3WIO59Dfc=
  app: quiet-beach-70340
